#!/usr/bin/env python3
"""
Output Builder for Incident Intelligence Agent Runtime.
Assembles, structures, and writes the final Incident Remediation Package.
"""

import os
import json
from pathlib import Path

class OutputBuilder:
    def __init__(self, packages_dir: str, traceability_id: str):
        """Initializes the output builder."""
        self.packages_dir = Path(packages_dir)
        self.traceability_id = traceability_id
        
        self.package_run_dir = self.packages_dir / self.traceability_id
        self.package_run_dir.mkdir(parents=True, exist_ok=True)

    def assemble_final_package(self, state: dict, logs: list) -> str:
        """Assembles all files in the package directory and returns the path."""
        # Save payload JSON
        payload_file = self.package_run_dir / f"{self.traceability_id}-remediation-payload.json"
        
        # Merge S1, S2, and S3 JSON data
        int_data = state.get("intermediate_data", {})
        merged_payload = {
            "traceability_id": self.traceability_id,
            "inputs": state.get("inputs", {}),
            "incident_analysis": int_data.get("incident_analysis_json", {}),
            "control_mapping": int_data.get("control_mapping_json", {}),
            "capability_validation": int_data.get("capability_validation_json", {}),
            "approvals": state.get("approvals", {})
        }
        
        payload_file.write_text(json.dumps(merged_payload, indent=2), encoding="utf-8")
        
        # Write audit logs
        log_file = self.package_run_dir / f"{self.traceability_id}-audit-log.jsonl"
        with open(log_file, "w", encoding="utf-8") as f:
            for log in logs:
                f.write(json.dumps(log) + "\n")
                
        # Write reports
        triage_report = int_data.get("incident_analysis_md", "# Incident Triage Report\n\nNo analysis generated.")
        (self.package_run_dir / f"{self.traceability_id}-incident-triage-report.md").write_text(triage_report, encoding="utf-8")
        
        remediation_plan = int_data.get("control_mapping_md", "# Operational Remediation Plan\n\nNo control mapping generated.")
        (self.package_run_dir / f"{self.traceability_id}-remediation-plan.md").write_text(remediation_plan, encoding="utf-8")
        
        verification_binder = int_data.get("verification_binder_md", "# Verification Binder\n\nNo verification binder generated.")
        (self.package_run_dir / f"{self.traceability_id}-verification-binder.md").write_text(verification_binder, encoding="utf-8")
        
        config_guide = int_data.get("config_guide_md", "# Ethana Configuration Guide\n\nNo config guide generated.")
        (self.package_run_dir / f"{self.traceability_id}-config-guide.md").write_text(config_guide, encoding="utf-8")
        
        # Write README
        readme_content = f"""# Incident Remediation Package — {self.traceability_id}

This directory contains the complete compliance and remediation package generated by the Cursory Governance OS Incident Intelligence Agent.

## Package Manifest:

*   [`README.md`](file://{self.package_run_dir}/README.md) - This manifest file.
*   [`{self.traceability_id}-incident-triage-report.md`](file://{self.package_run_dir}/{self.traceability_id}-incident-triage-report.md) - Executive triage, 5-Whys root cause, and failed control registry.
*   [`{self.traceability_id}-remediation-plan.md`](file://{self.package_run_dir}/{self.traceability_id}-remediation-plan.md) - Detailed specifications for preventive, detective, and corrective controls with RACI matrix.
*   [`{self.traceability_id}-verification-binder.md`](file://{self.package_run_dir}/{self.traceability_id}-verification-binder.md) - Evidence logs registry and checklist to prove control operational effectiveness.
*   [`{self.traceability_id}-config-guide.md`](file://{self.package_run_dir}/{self.traceability_id}-config-guide.md) - Validated platform parameters and manual workarounds for roadmap dependencies.
*   [`{self.traceability_id}-remediation-payload.json`](file://{self.package_run_dir}/{self.traceability_id}-remediation-payload.json) - Full machine-readable workflow payload data.
*   [`{self.traceability_id}-audit-log.jsonl`](file://{self.package_run_dir}/{self.traceability_id}-audit-log.jsonl) - Immutable run audit trail verifying all transitions and human approvals.
"""
        (self.package_run_dir / "README.md").write_text(readme_content, encoding="utf-8")
        
        return str(self.package_run_dir)
